const Types: string[] = ["DHL", "Hellmann", "Logwin"];

export const carrierMappings: Record<string, any> = {
    dhl: {
        carriertypes: Types[0],
        status: "Last Checkpoint Code",
        po_number: "Shipper Reference Number",
        eta: "Estimated Delivery Date",
        etd: null,
        atd: null,
        ata: "Latest Checkpoint Date/Time",
        packages: "Pieces",
        volume: null,
        weight: "Manifested Weight",
        shipper: "Shipper Reference Number",
        shipper_country: "Origin Country/Territory IATA code",
        receiver: "Receiver",
        receiver_country: "Destination Country/Territory IATA code",
        houseawb: "Waybill Number",
        shipper_ref_no: "Shipper Reference Number",
        carrier: "DHL",
        inco_term: null,
        vessel_flight: null,
        pickup_date: "Pickup Date",
        latest_cp: "Latest Checkpoint",
    },
    hellmann: {
        carriertypes: Types[1],
        status: "Status",
        po_number: null,
        eta: "Flight ETA",
        etd: "Flight ETD",
        atd: "Flight ATD",
        ata: "Flight ATA",
        packages: "No of Packages",
        weight: "Gross Weight (Kg)",
        volume: null,
        shipper: "Shipper Name",
        shipper_country: "Shipper Country",
        receiver: "Consignee Name",
        receiver_country: "Consignee Country",
        houseawb: "House AWB",
        shipper_ref_no: null,
        carrier: "Hellmann",
        inco_term: "Incoterm",
        vessel_flight: "Flight No",
        pickup_date: "Act. Pick Up",
        latest_cp: null,
    },
    logwin: {
        carriertypes: null,
        status: "Status",
        po_number: "PO Number",
        eta: "ETA",
        etd: "ETD",
        atd: "ATD",
        ata: "ATA",
        packages: "Packages",
        weight: "Weight",
        volume: "Volume",
        shipper: "Shipper",
        shipper_country: "Port of Origin",
        receiver: "Consignee",
        receiver_country: "Port of Destination",
        houseawb: "House",
        shipper_ref_no: "Shipper Ref.",
        carrier: "Carrier",
        inco_term: null,
        vessel_flight: "Voyage / Flight",
        pickup_date: null,
        latest_cp: null,
    },
}
